
contrail::admin_password: mnVjZCxhYgtkXd8Myy6VhaC2n
contrail::admin_tenant_name: admin
contrail::admin_token: w4NP8GNB6h9Mx4XzFHfbyn76V
contrail::admin_user: admin
contrail::rabbit_user: guest
contrail::rabbit_password: affVJcd6udkPCBr9VfZCYFJ8d
contrail::analytics::collector_http_server_port: 8089
contrail::analytics::collector_sandesh_port: 8086
contrail::analytics::host_ip: 127.0.0.1
contrail::analytics::http_server_port: 8090
contrail::analytics::listen_ip_address: 0.0.0.0
contrail::analytics::listen_port: 8082
contrail::analytics::redis_server: 127.0.0.1
contrail::analytics::redis_server_port: 6379
contrail::analytics::rest_api_ip: 0.0.0.0
contrail::analytics::rest_api_port: 8081
contrail::analytics::rabbit_server: 192.0.2.17:5672
contrail::auth: keystone
contrail::auth_host: 192.0.2.17
contrail::auth_port: 5000
contrail::auth_protocol: http
contrail::cassandra_server_list: [
  "192.0.2.10"
]
contrail::config::ifmap_password: api-server
contrail::config::ifmap_server_ip: 127.0.0.1
contrail::config::ifmap_username: api-server
contrail::config::listen_ip_address: 0.0.0.0
contrail::config::listen_port: 8082
contrail::config::rabbit_server: 192.0.2.17:5672
contrail::config::redis_server: 127.0.0.1
contrail::control::host_ip: 127.0.0.1
contrail::control::ifmap_password: control
contrail::control::ifmap_username: control
contrail::control::rndc_secret: "sHE1SM8nsySdgsoRxwARtA=="
contrail::control_server_list: [
  "192.0.2.10"
]
contrail::database::host_ip: 127.0.0.1
contrail::database::minimum_diskGB: 64
contrail::disc_server_ip: 127.0.0.1
contrail::disc_server_port: 5998
contrail::insecure: false
contrail::kafka_broker_list: [
  "127.0.0.1"
]
contrail::memcached_server: 127.0.0.1:12111
contrail::multi_tenancy: true
contrail::webui::contrail_analytics_vip: 127.0.0.1
contrail::webui::contrail_config_vip: 127.0.0.1
contrail::webui::contrail_neutron_vip: 192.0.2.17
contrail::webui::contrail_webui_http_port: 8080
contrail::webui::contrail_webui_https_port: 8143
contrail::webui::neutron_vip: 127.0.0.1
contrail::webui::redis_ip: 127.0.0.1
contrail::zk_server_ip: [
  "192.0.2.10"
]
contrail::zk_hostnames: "host1"
cassandra_ip: 127.0.0.1
cassandra_servers: [
  "192.0.2.10:9160"
]
zookeeper::params::packages: [
  "zookeeper-3.4.8-0.contrail1.el7.centos.x86_64"
]
zookeeper::params::service_name: zookeeper
